backend:
  name: github
  repo: ismaeldevmw/creative-portfolio # Path to your Github repository
  branch: master # Branch to update

publish_mode: editorial_workflow

media_folder: "img/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "portfolio" # Used in routes, e.g., /admin/collections/blog
    label: "Portfolio" # Used in the UI
    folder: "_portfolio" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{project_name}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Image", name: "image_path",  widget: "image", required: true}
      - {label: "Category", name: "category", widget: "string",  required: true}
      - {label: "Project name", name: "project_name", widget: "string", required: true}
      - {label: "Link", name: "link", widget: "string" }
